using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class All : MonoBehaviour
{
    public void Allthing(string name)
    {
        switch (name)
        {
            case "Bed":
            case "BirthdayCake":
            case "Book001":
            case "Book002":
            case "Book003":
            case "Book004":
            case "Book005":
            case "Book006":
            case "Book007":
            case "Book008":
            case "Book009":
            case "Book010":
            case "Book011":
            case "Book012":
            case "Bowl001":
            case "Bowl002":
            case "Bowl003":
            case "Bowl004":
            case "Bowl005":
            case "Box006":
            case "Box007":
            case "CabinetDoor001":
            case "CabinetDoor002":
            case "Cellphone":
            case "Chair001":
            case "Chair002":
            case "Chair003":
            case "Chair004":
            case "Chair005":
            case "Chair006":
            case "Chair007":
            case "Chair008":
            case "Clock":
            case "Clothes":
            case "Clothes006":
            case "Clothes007":
            case "Clothes008":
            case "Clothes009":
            case "Computer":
            case "Cup001":
            case "Cup002":
            case "Cup003":
            case "Cup004":
            case "Cup005":
            case "CuttingBoard001":
            case "CuttingBoard002":
            case "CuttingBoard003":
            case "DeskLamp":
            case "DogFoods":
            case "Drawer001":
            case "Drawer002":
            case "Drawer003":
            case "Drawer004":
            case "Drawer005":
            case "Flower":
            case "GasStove":
            case "IceCreamBox001":
            case "IceCreamBox002":
            case "IceCreamBox003":
            case "Kennel":
            case "Letter001":
            case "Letter002":
            case "Letter003":
            case "Letter004":
            case "Magnifier":
            case "MonthlyCalendar":
            case "Pan":
            case "Paste":
            case "Pen001":
            case "Pen002":
            case "Pen003":
            case "Pen004":
            case "Pen005":
            case "Pen006":
            case "Pen007":
            case "PenHolder":
            case "PhotoFrame":
            case "Plate001":
            case "Plate002":
            case "Plate003":
            case "Plate004":
            case "Plate005":
            case "PopsicleBox001":
            case "PopsicleBox002":
            case "PopsicleBox003":
            case "PopsicleBox004":
            case "Refrigerator003":
            case "Milkv":
            case "AluminumCan001":
            case "AluminumCan002":
            case "AluminumCan003":
            case "AluminumCan004":
            case "Wine001":
            case "Wine002":
            case "Wine003":
            case "Scissors":
            case "Seasoning001":
            case "Seasoning002":
            case "Seasoning003":
            case "Seasoning004":
            case "Seasoning005":
            case "Shelf002":
            case "Sink":
            case "SlidingDoor001":
            case "SlidingDoor002":
            case "SlidingDoor003":
            case "SlidingDoor004":
            case "Spatula":
            case "Spoon":
            case "Table001":
            case "Table002":
            case "Table003":
            case "Table004":
            case "Wardrobe":
            case "WardrobeDoor001":
            case "WardrobeDoor002":
            case "Watermelon001":
            case "Watermelon002":
            case "Picture":
            case "DogBowl":
                break;
            default:
                break;
        }
    }
}
